[theme]
primaryColor = "#1E40AF"
backgroundColor = "#F1F5F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
